name: GitHub Packages deployment & Discord notification

on:
  workflow_call:
    inputs:
      unsafe:
        type: boolean
        default: false
        required: false
    secrets:
      node_auth_token:
        required: true
      discord_webhook:
        required: true

jobs:
    publish:
      uses: Depra-Inc/Workflows/.github/workflows/publish-package.yml@main
      secrets:
        token: ${{secrets.node_auth_token}}
      with:
        domain: npm.pkg.github.com
        registry: https://npm.pkg.github.com/@${{github.repository_owner}}
        unsafe: ${{inputs.unsafe}}
  
    notify:
      needs: publish
      if: needs.publish.outputs.published == 'true'
      uses: Depra-Inc/Workflows/.github/workflows/notify-discord.yml@main
      secrets:
        discord_webhook: ${{secrets.discord_webhook}}
      with:
        avatar_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        discord_username: Depra [GitHub Packages]
        package_name: ${{needs.publish.outputs.package_name}}
        package_version: ${{needs.publish.outputs.package_version}}