name: NPM deployment & Discord notification

on:
  workflow_call:
    inputs:
      unsafe:
        type: boolean
        default: false
        required: false
    secrets:
      node_auth_token:
        required: true
      discord_webhook:
        required: true

jobs:
    publish:
      uses: Depra-Inc/Workflows/.github/workflows/publish-npr.yml@main
      secrets:
        token: ${{secrets.node_auth_token}}
      with:
        domain: depra.org
        registry: https://depra.org/npm
        unsafe: ${{inputs.unsafe}}
  
    notify:
      needs: publish
      if: needs.publish.outputs.published == 'true'
      uses: Depra-Inc/Workflows/.github/workflows/notify-discord.yml@main
      secrets:
        discord_webhook: ${{secrets.discord_webhook}}
      with:
        avatar_url: 'https://i.postimg.cc/1VVMf4L1/npm.png'
        discord_username: 'Depra [NPM]'
        package_name: ${{needs.publish.outputs.package_name}}
        package_version: ${{needs.publish.outputs.package_version}}