name: Checkout package repository

on: [workflow_call]

env:
  workflows_repository: Workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout repository
        uses: actions/checkout@v4

      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: .