name: Publishing a package to GitHub

on:
  workflow_call:
    inputs:
      scope: 
        type: string
        required: false
      domain:
        type: string
        required: true
      registry:
        type: string
        required: true
    outputs:
      package_name:
        description: "Package name"
        value: ${{jobs.publish.outputs.package_name}}
      package_version:
        description: "Package version"
        value: ${{jobs.publish.outputs.package_version}}
    secrets:
      token:
        required: true 

env:
  workflows_repository: Workflows

jobs:
  publish:
    runs-on: ubuntu-latest

    outputs:
      package_name: ${{steps.semantic.outputs.name}}
      package_version: ${{steps.semantic.outputs.version}}

    steps:
      - name: Chechout this repository
        uses: actions/checkout@v4

      - name: Checkout reusable workflows repository
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository_owner}}/${{env.workflows_repository}}
          path: ${{env.workflows_repository}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '14.x'
          scope: ${{inputs.scope}}
          registry-url: ${{inputs.registry}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.token}}

      - name: Install dependencies
        run: npm install

      #- name: Authenticate to NPM
      #  run: |
      #    echo "//${{inputs.domain}}/:_authToken=${{secrets.token}}
      #    ${{inputs.scope}}:registry=${{inputs.registry}}" >> .npmrc
      #    cat .npmrc
      #    npm whoami
    
      - name: Semantic release
        id: semantic
        run: |
          chmod +x ${{env.workflows_repository}}/.github/scripts/semantic-release.sh
          ${{env.workflows_repository}}/.github/scripts/semantic-release.sh

      - name: Publish to package registry
        if: steps.semantic.outputs.status == 'success'
        run: npm publish