name: Release notification on Discord

on:
  workflow_call:
    inputs:
      avatar_url:
        type: string
        required: true
      package_name:
        type: string
        required: true
      package_version:
        type: string
        required: true
      discord_username:
        type: string
        required: true
    secrets:
      discord_webhook:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve author
        id: resolve_author
        run: |
          if [ -z "${{github.event.head_commit.author.name}}" ]; then
            echo "author_name=${{github.actor}}" >> $GITHUB_OUTPUT
          else
            echo "author_name=${{github.event.head_commit.author.name}}" >> $GITHUB_OUTPUT
          fi

      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{secrets.discord_webhook}}
          DISCORD_USERNAME: ${{inputs.discord_username}}
          DISCORD_AVATAR: ${{inputs.avatar_url}}
          DISCORD_EMBEDS: '[    { 
            "author": {  "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "name": "${{ github.actor }}", "url": "https://github.com/${{github.actor}}" },
            "url": "https://github.com/${{github.repository}}/commit/${{github.sha}}",
            "fields": [
            { "name": "Repository", "value": "[${{github.event.repository.name}}](${{github.event.repository.clone_url}})", "inline": true },
            { "name": "Branch", "value": "[${{github.ref_name}}](https://github.com/${{github.repository}}/tree/${{github.ref_name}})", "inline": true },
            { "name": "Package", "value": "📦 `${{inputs.package_name}}@${{inputs.package_version}}`" },
            { "name": "Author", "value": "[${{steps.resolve_author.outputs.author_name}}](https://github.com/${{github.actor}})" }
            ],
            "color":1127128,
            "timestamp": "${{github.event.head_commit.timestamp}}",
            "footer":{"text": "${{github.event.head_commit.timestamp}}"}
            }    ]'