name: Publishing a package

on:
  workflow_call:
    inputs:
      domain:
        type: string
        required: true
      registry:
        type: string
        required: true
    outputs:
      package_name:
        value: ${{jobs.publish.outputs.package_name}}
      package_version:
        value: ${{jobs.publish.outputs.package_version}}
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    outputs:
      package_name: ${{steps.semantic.outputs.name}}
      package_version: ${{steps.semantic.outputs.version}}

    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v3
        with:
          name: package
  
      - name: Download workflows artifacts
        uses: actions/download-artifact@v3
        with:
          name: scripts

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Authenticate to NPM
        run: |
          echo "//${{inputs.domain}}/:_authToken=${{secrets.token}}
          registry=${{inputs.registry}}" >> .npmrc

      - name: Compare npm with local (versions)
        uses: Rober19/compare-npm-versions-ci@master
        id: package_version
        with:
          path: './'
          npm_package_name: $(jq -r '.name' package.json)

      - name: Get version
        run: |
          echo "Version is  ${{ steps.package_version.outputs.version }} "    
          echo "Version NPM is  ${{ steps.package_version.outputs.pkg_npm_version }} "

      - name: Semantic release
        id: semantic
        run: chmod +x ./semantic-release.sh && ./semantic-release.sh

      - name: Publish to package registry
        if: steps.semantic.outputs.status == 'success'
        run: npm publish