name: GitHub Packages publishing

on:
  workflow_call:
    inputs:
      domain:
        type: string
        required: true
      registry:
        type: string
        required: true
      scope:
        type: string
        required: false
      unsafe:
        type: boolean
        default: false
        required: false
    outputs:
      published:
        value: ${{jobs.publish.outputs.published}}
      package_name:
        value: ${{jobs.publish.outputs.package_name}}
      package_version:
        value: ${{jobs.publish.outputs.package_version}}
    secrets:
      token:
        required: true

env:
  workflows_repository: Workflows

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      published: ${{steps.publish.outputs.published}}
      package_name: ${{steps.semantic.outputs.name}}
      package_version: ${{steps.semantic.outputs.version}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Patch .npmrc
        uses: Depra-Inc/Setup.Npmrc@main
        with:
          scope: ${{inputs.scope}}
          token: ${{secrets.token}}
          domain: ${{inputs.domain}}
          registry: ${{inputs.registry}}

      - name: Install dependencies
        if: ${{inputs.unsafe == false}}
        run: npm install

      - name: Semantic version validation
        id: semantic
        uses: Depra-Inc/SemVer.Guard@main

      - name: Publish to package registry
        id: publish
        if: steps.semantic.outputs.increased == 'true'
        run: |
          npm publish
          echo "published=true" >> $GITHUB_OUTPUT